name: LeslieGroup
favicon: null
layout_spectrum: 0.9812149896752089
typography_spectrum: 0.267970402026549
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.4036644035950303
  lightness: 0.8308973191305995
  saturation: 0.22753560822457075
  rhythmicContrast: 0.07710396545007825
purpose: []
