name: LeslieGroup
favicon: null
layout_spectrum: 0.43384
typography_spectrum: 0.37455
title: Finding the best talent matched with the best opportunity
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#4b7313'
    - '#1e4206'
    - '#c2ce4f'
  brandStrength: 0.625
  lightness: 0.1875
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
